// Mocks generated by Mockito 5.4.6 from annotations
// in chatas/test/features/friends/presentation/pages/friends_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:chatas/features/friends/domain/usecases/block_friend_usecase.dart'
    as _i3;
import 'package:chatas/features/friends/domain/usecases/get_friends_usecase.dart'
    as _i2;
import 'package:chatas/features/friends/presentation/cubit/friends_list_cubit.dart'
    as _i4;
import 'package:flutter/widgets.dart' as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:go_router/src/configuration.dart' as _i5;
import 'package:go_router/src/delegate.dart' as _i7;
import 'package:go_router/src/information_provider.dart' as _i8;
import 'package:go_router/src/match.dart' as _i15;
import 'package:go_router/src/parser.dart' as _i9;
import 'package:go_router/src/router.dart' as _i13;
import 'package:go_router/src/state.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetFriendsUseCase_0 extends _i1.SmartFake
    implements _i2.GetFriendsUseCase {
  _FakeGetFriendsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBlockFriendUseCase_1 extends _i1.SmartFake
    implements _i3.BlockFriendUseCase {
  _FakeBlockFriendUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendsState_2 extends _i1.SmartFake implements _i4.FriendsState {
  _FakeFriendsState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_3 extends _i1.SmartFake
    implements _i5.RouteConfiguration {
  _FakeRouteConfiguration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_4 extends _i1.SmartFake
    implements _i6.BackButtonDispatcher {
  _FakeBackButtonDispatcher_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_5 extends _i1.SmartFake
    implements _i7.GoRouterDelegate {
  _FakeGoRouterDelegate_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_6 extends _i1.SmartFake
    implements _i8.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_7 extends _i1.SmartFake
    implements _i9.GoRouteInformationParser {
  _FakeGoRouteInformationParser_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterState_8 extends _i1.SmartFake implements _i10.GoRouterState {
  _FakeGoRouterState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FriendsListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsListCubit extends _i1.Mock implements _i4.FriendsListCubit {
  MockFriendsListCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetFriendsUseCase get getFriendsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getFriendsUseCase),
            returnValue: _FakeGetFriendsUseCase_0(
              this,
              Invocation.getter(#getFriendsUseCase),
            ),
          )
          as _i2.GetFriendsUseCase);

  @override
  _i3.BlockFriendUseCase get blockFriendUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#blockFriendUseCase),
            returnValue: _FakeBlockFriendUseCase_1(
              this,
              Invocation.getter(#blockFriendUseCase),
            ),
          )
          as _i3.BlockFriendUseCase);

  @override
  _i4.FriendsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeFriendsState_2(this, Invocation.getter(#state)),
          )
          as _i4.FriendsState);

  @override
  _i11.Stream<_i4.FriendsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i11.Stream<_i4.FriendsState>.empty(),
          )
          as _i11.Stream<_i4.FriendsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i11.Future<void> loadFriends(String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#loadFriends, [currentUserId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> blockFriend(String? currentUserId, String? friendId) =>
      (super.noSuchMethod(
            Invocation.method(#blockFriend, [currentUserId, friendId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> unblockFriend(String? currentUserId, String? friendId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockFriend, [currentUserId, friendId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> toggleBlockFriend(
    String? currentUserId,
    String? friendId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBlockFriend, [currentUserId, friendId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> refreshFriends(String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshFriends, [currentUserId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void clearMessage() => super.noSuchMethod(
    Invocation.method(#clearMessage, []),
    returnValueForMissingStub: null,
  );

  @override
  void searchFriends(String? query) => super.noSuchMethod(
    Invocation.method(#searchFriends, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.FriendsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i12.Change<_i4.FriendsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i13.GoRouter {
  MockGoRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_3(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i5.RouteConfiguration);

  @override
  _i6.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_4(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i6.BackButtonDispatcher);

  @override
  _i7.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_5(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i7.GoRouterDelegate);

  @override
  _i8.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_6(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i8.GoRouteInformationProvider);

  @override
  _i9.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_7(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i9.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
          )
          as bool);

  @override
  _i10.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_8(this, Invocation.getter(#state)),
          )
          as _i10.GoRouterState);

  @override
  set configuration(_i5.RouteConfiguration? _configuration) =>
      super.noSuchMethod(
        Invocation.setter(#configuration, _configuration),
        returnValueForMissingStub: null,
      );

  @override
  set routerDelegate(_i7.GoRouterDelegate? _routerDelegate) =>
      super.noSuchMethod(
        Invocation.setter(#routerDelegate, _routerDelegate),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationProvider(
    _i8.GoRouteInformationProvider? _routeInformationProvider,
  ) => super.noSuchMethod(
    Invocation.setter(#routeInformationProvider, _routeInformationProvider),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationParser(
    _i9.GoRouteInformationParser? _routeInformationParser,
  ) => super.noSuchMethod(
    Invocation.setter(#routeInformationParser, _routeInformationParser),
    returnValueForMissingStub: null,
  );

  @override
  bool canPop() =>
      (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false)
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i15.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i11.Future<T?>.value(),
          )
          as _i11.Future<T?>);

  @override
  _i11.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i11.Future<T?>.value(),
          )
          as _i11.Future<T?>);

  @override
  _i11.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i11.Future<T?>.value(),
          )
          as _i11.Future<T?>);

  @override
  _i11.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i11.Future<T?>.value(),
          )
          as _i11.Future<T?>);

  @override
  _i11.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i11.Future<T?>.value(),
          )
          as _i11.Future<T?>);

  @override
  _i11.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i11.Future<T?>.value(),
          )
          as _i11.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
