// Mocks generated by Mockito 5.4.6 from annotations
// in chatas/test/features/chat_thread/domain/get_chat_threads_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chatas/features/chat_thread/domain/entities/chat_thread.dart'
    as _i4;
import 'package:chatas/features/chat_thread/domain/repositories/chat_thread_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChatThreadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatThreadRepository extends _i1.Mock
    implements _i2.ChatThreadRepository {
  MockChatThreadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ChatThread>> getChatThreads() =>
      (super.noSuchMethod(
            Invocation.method(#getChatThreads, []),
            returnValue: _i3.Future<List<_i4.ChatThread>>.value(
              <_i4.ChatThread>[],
            ),
          )
          as _i3.Future<List<_i4.ChatThread>>);
}
