// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW6f2Ptc4pulh6nYQ8P0RfvaDybXPZRpk',
    appId: '1:65608364554:web:21f87aea70fead699525f3',
    messagingSenderId: '65608364554',
    projectId: 'chatas-9469d',
    authDomain: 'chatas-9469d.firebaseapp.com',
    storageBucket: 'chatas-9469d.firebasestorage.app',
    measurementId: 'G-E1PE3G2SF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-HWGrSylbqQERRyVwoTl66smZ84qq9I',
    appId: '1:65608364554:android:b310985c2a05baa19525f3',
    messagingSenderId: '65608364554',
    projectId: 'chatas-9469d',
    storageBucket: 'chatas-9469d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6PZ28rNgyptdCDwl7Y6wU2Btc9-nuyQ',
    appId: '1:65608364554:ios:c87cf3437853f0bd9525f3',
    messagingSenderId: '65608364554',
    projectId: 'chatas-9469d',
    storageBucket: 'chatas-9469d.firebasestorage.app',
    iosBundleId: 'com.example.chatas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6PZ28rNgyptdCDwl7Y6wU2Btc9-nuyQ',
    appId: '1:65608364554:ios:c87cf3437853f0bd9525f3',
    messagingSenderId: '65608364554',
    projectId: 'chatas-9469d',
    storageBucket: 'chatas-9469d.firebasestorage.app',
    iosBundleId: 'com.example.chatas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW6f2Ptc4pulh6nYQ8P0RfvaDybXPZRpk',
    appId: '1:65608364554:web:2099d03b5c3fc7129525f3',
    messagingSenderId: '65608364554',
    projectId: 'chatas-9469d',
    authDomain: 'chatas-9469d.firebaseapp.com',
    storageBucket: 'chatas-9469d.firebasestorage.app',
    measurementId: 'G-N313KVH38Y',
  );
}
