name: CD

# Triggers cho deployment
on:
  push:
    tags:
      - 'v*.*.*'  # Trigger khi push tag version (v1.0.0, v2.1.3, etc.)
  workflow_dispatch:  # Cho phép trigger manual

jobs:
  # Job 1: Deploy to Firebase App Distribution
  deploy-android-staging:
    name: Deploy Android to Firebase App Distribution
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    # Build APK với signing (cần setup keystore)
    - name: Build APK
      run: flutter build apk --release
      
    # Deploy to Firebase App Distribution
    - name: Deploy to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        groups: testers
        file: build/app/outputs/flutter-apk/app-release.apk
        releaseNotes: |
          Release ${{ github.ref_name }}
          
          Changes in this release:
          - Bug fixes and improvements
          - Performance optimizations

  # Job 2: Deploy Web to Firebase Hosting
  deploy-web:
    name: Deploy Web to Firebase Hosting
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        channelId: live

  # Job 3: Create GitHub Release
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [deploy-android-staging, deploy-web]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build Web
      run: flutter build web --release
      
    # Tạo release với artifacts
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
        body: |
          ## Chatas App Release ${{ github.ref_name }}
          
          ### ✨ New Features
          - Add your new features here
          
          ### 🐛 Bug Fixes
          - Add your bug fixes here
          
          ### 🔧 Improvements
          - Add your improvements here
          
          ### 📱 Installation
          - **Android**: Download the APK file below
          - **Web**: Visit [https://your-app.web.app](https://your-app.web.app)
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
